<?php namespace JF;
/**

Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-7ee7e2
Date:    2017-05-30 08:25:51
Version: v2.0.1
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-7ee7e2",
    "email": {
        "to": "test@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "testers {f1}{f4}",
        "template": ""
    },
    "admin": {
        "users": "admin:681d5",
        "dataDelivery": "emailAndFile",
        "limitActivity": {
            "enabled": false,
            "by": "email"
        }
    },
    "thankyou": {
        "url": "",
        "message": "Your form has been sent. Thank You {f1} {f4}!",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "ContaForm",
        "description": "Contact Form",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "orange"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "First Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "firstname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": ""
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Last Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "lastname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "equalto": {
                        "enabled": false
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": "254"
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "3"
                    }
                },
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Confirm Email",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": true,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "3"
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": "254"
                    }
                }
            },
            "id": "f5",
            "cid": "c32"
        },
        {
            "label": "Date of Birth",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "",
                    "rightText": "",
                    "leftIcon": "fa fa-calendar"
                },
                "date": {
                    "startView": "2",
                    "minViewMode": "0",
                    "multidate": "false",
                    "weekStart": "1",
                    "endDate": "-6570d",
                    "startDate": "-44895d",
                    "format": "dd\/mm\/yyyy"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f6",
            "cid": "c37"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class