# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Simple Weave Theme"
license = "MIT"
licenselink = "https://github.com/GeorgeWL/weavability-hugo/blob/master/LICENSE.md"
description = "Weavability Site made for a Interview Process"
homepage = "https://github.com/GeorgeWL/weavability-hugo"
tags = ["business","company","minimal"]
features = ["search","responsive","bootstrap","TapirGo"]
min_version = "0.20.7"

[author]
  name = "GeorgeWL"
  homepage = "https://georgelangham.me"
